version: "3.7"
services:
  scraping:
    build:
      context: .
    image: 705373246515.dkr.ecr.ap-northeast-2.amazonaws.com/related-keyword-extractor:0.0.3
    ports:
      - 8080:8080
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      REDIS_HOST: nodeport.eevl.studio
      REDIS_PORT: 30224
      REDIS_DB_NUM: 1
    volumes:
      - .:/app